AndyQV/SoftEdge

Back/controllers/ai.controllers.js
Front/src/pages/Generate.jsx

Prompt estructurado de regreso.

Esqueleto1

---

Back/index.js

Las rutas dejaron de existir y las regrese a la Thanos 2.0

Arreglando las rutas

---

Front/src/css/RevisionIA.css
Front/src/pages/RevisionIA.jsx

Todo los edits sin guardar

---

Front/src/pages/RevisionIA.jsx

Rodrigo fan #1 de crear pull requests

Ahora se guarda

---

Front/src/pages/RevisionIA.jsx

Ya funciona el post y editar todo

---

Back/controllers/projectsFB.controllers.js
Back/package-lock.json
Back/package.json
Back/routes/projectsFB.routes.js
Back/utils/firebase.js
Front/src/components/ImageUpload.jsx
Front/src/pages/Home.jsx

Integrado:
- Obtener proyectos basado en el ID del usuario y la tabla usuarios_proyectos en SQL.
- Back para guardar imagenes en cada proyecto
Falta:
- Activar Firebase Storage (se necesita cuenta de pago [no pagar, pero la cuenta])
- Implementar el front

Proyectos por usuario y back para subir imagenes (falta activar firebase storage)

---

Front/src/pages/Home.jsx

Arreglando

---

Front/src/pages/Home.jsx

Me encanta arreglar esto

---

Back/controllers/projectsFB.controllers.js
Front/src/pages/Dashboard.jsx
Front/src/pages/Login.jsx

Dashboard basico

---

Front/src/App.jsx
Front/src/components/AuthContext.jsx
Front/src/components/UserContext.jsx
Front/src/main.jsx
Front/src/pages/Home.jsx
Front/src/pages/Login.jsx

Odio gestionar usuarios

---

Back/index.js
Back/package-lock.json
Back/package.json
Back/utils/sql.js
Back/utils/vercel.json

Faltan las rutasa y borrar el localhost

Setup para deploy de back

---

Back/controllers/login.controllers.js
Back/package-lock.json
Back/package.json
Back/routes/projectsFB.routes.js
Back/utils/auth.middleware.js
Front/src/App.jsx
Front/src/components/AuthContext.jsx
Front/src/components/TopAppBar.jsx
Front/src/components/UserContext.jsx
Front/src/css/Login.css
Front/src/css/index.css
Front/src/pages/Dashboard.jsx
Front/src/pages/Home.jsx
Front/src/pages/Login.jsx
Front/src/pages/RevisionIA.jsx

Agregada seguridad con JWT a las rutas, asi como timeout y el boton de logout (porfin)

JSON Web Token y Cerrar Sesion

---

Front/src/css/Dashboard.css
Front/src/pages/Dashboard.jsx

Todo agregar tareas menos subida a base de datos

---

Front/src/pages/Dashboard.jsx

cambios drag and drop

---

Back/controllers/login.controllers.js
Front/src/css/Dashboard.css
Front/src/pages/Dashboard.jsx

Ya esta el poder agregar tareas pero no se manda aun a base de datos

Tareas implementado sin base de datos

---

Front/src/components/RenderRequirementsTab.jsx
Front/src/components/TeamContainer.jsx
Front/src/pages/Dashboard.jsx

Usen componentes

---

Front/src/components/EditMemeberPopup.jsx
Front/src/components/TeamContainer.jsx
Front/src/pages/Dashboard.jsx

usen componentes porfavor jaja

Moviendo mas cosas

---

Back/controllers/login.controllers.js
Front/src/pages/Home.jsx

Deje el timer en 3s jaja

---

Back/controllers/projectsFB.controllers.js
Back/routes/projectsFB.routes.js
Front/src/components/TeamEditPopup.jsx
Front/src/pages/Dashboard.jsx

Ya se puede agregar y remover usuarios de cada proyecto

Manejo de usuarios

---

Back/controllers/projectsFB.controllers.js
Front/src/components/ModificationHistory.jsx
Front/src/components/RenderRequirementsTab.jsx
Front/src/components/TeamEditPopup.jsx
Front/src/css/Dashboard.css
Front/src/css/DragAndDropTable.css
Front/src/css/Generate.css
Front/src/css/ModificationHistory.css
Front/src/pages/Dashboard.jsx
Front/src/pages/Generate.jsx

Mayormente estilo, pero agregué búsqueda en miembros de equipo

Cambios de recomendaciones

---

Front/src/components/RenderRequirementsTab.jsx
Front/src/css/Dashboard.css
Front/src/pages/Dashboard.jsx
Front/src/pages/Generate.jsx
Front/src/pages/RevisionIA.jsx

Back creacion de tareas con AI y cambios algunos fronts

---

Back/controllers/projectsFB.controllers.js
Back/routes/projectsFB.routes.js
Front/src/components/RenderRequirementsTab.jsx
Front/src/pages/Dashboard.jsx
Front/src/pages/Generate.jsx

Rodrigo no sabe prompt eingineering

---

Back/controllers/projectsFB.controllers.js
Front/src/css/RevisionIA.css
Front/src/css/index.css
Front/src/pages/Dashboard.jsx

Ya se pueden eliminar con confirmacion

Eliminar proyectos

---

Front/src/components/PerfilPopup.jsx
Front/src/components/SuccessPopup.jsx
Front/src/components/TopAppBar.jsx
Front/src/css/Perfil.css
Front/src/pages/Generate.jsx
Front/src/pages/Perfil.jsx
package.json

Aqui le va mi parte de la deuda, por ahora seguire trabajando 
Buenas tardes
Saludos diizon vazquez

Parte de la deuda

---

Front/src/css/Perfil.css

Aqui estan las mejoras del popup 
A seguir chambeanding
Gracias

Mejoras en el popup perfil

---

Front/src/components/RenderRequirementsTab.jsx

La pantalla del equipo StratEdge brillaba con el código, una maraña de líneas que representaba la ambición del proyecto. Samuel, con la mirada fija en el monitor, sentía la punzada de una tarea pendiente: el botón. No era un botón cualquiera; era el corazón de una interacción crucial en su página de React, una pieza clave para la usabilidad y la experiencia del usuario. Llevaba días batallando con él, depurando, reajustando, como un relojero que intenta que una diminuta pieza encaje a la perfección.
Hoy, sin embargo, el aire en la oficina de Monterrey era diferente. Una sonrisa se dibujó en su rostro mientras tecleaba las últimas líneas. "¡Lo tenemos!", exclamó, casi para sí mismo. Era una sensación de alivio y triunfo. No estaba terminado del todo, pero sabía que había cruzado un um …

La mitad del boton de Samuel ya esta arreglado

---

Front/src/components/PerfilPopup.jsx
Front/src/components/RenderRequirementsTab.jsx
Front/src/css/Home.css
Front/src/css/Perfil.css
Front/src/css/RevisionIA.css
Front/src/pages/Dashboard.jsx
Front/src/pages/RevisionIA.jsx

Los cambios estan hecho otra vez

---

Front/src/components/ProjectCard.jsx
Front/src/pages/Home.jsx
Front/src/pages/RevisionIA.jsx

Ya quedo el sort por colores y el problema de los dobles clicks en revision IA
Saludos cordiales - Samuel Gonzalez Vazquez

Quedaron unas cosillas

---

Back/controllers/projectsFB.controllers.js
Front/src/components/PerfilPopup.jsx
Front/src/css/Perfil.css
Front/src/pages/Generate.jsx
Front/src/pages/RevisionIA.jsx

Ya arregle el popup de perfil y un boton rojo

Arregle unos estilos bugeados

---

Front/src/css/InsertElement.css
Front/src/pages/Dashboard.jsx

Una disculpa team no me percate que a la hora de hacer commits el css que cree cambio unos botones, pero ya quedaron arreglados.
Con cariño, Samu Gonz.

Arreglando estilos

---

Front/src/components/ProjectMetrics.jsx
Front/src/pages/Dashboard.jsx

Mas cosas con sprints
